name = "shopbgremover-api"
main = "worker/index.js"
compatibility_date = "2026-07-23"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[observability.logs]
enabled = true
head_sampling_rate = 1

[observability.traces]
enabled = true
head_sampling_rate = 0.05

[[d1_databases]]
binding = "DB"
database_name = "shopbgremover-db"
database_id = "f9c622b0-9360-48c1-a2a6-36e51b93d3de"
migrations_dir = "worker/migrations"

[vars]
FRONTEND_URL = "https://www.shopbgremover.com"
NEXTAUTH_URL = "https://www.shopbgremover.com"
ADMIN_EMAILS = "yubudong2023@gmail.com"

[triggers]
crons = ["17 * * * *"]

[[routes]]
pattern = "api.shopbgremover.com/*"
zone_name = "shopbgremover.com"
